version: "3.9"
services:
  db:
    image: postgres:16
    container_name: flipapp_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    # Exponer para uso local (pgadmin, etc.). Si no lo necesitas, elimina esta línea.
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: flipapp_backend
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/appdb
      JWT_SECRET_KEY: supersecret
      STORAGE_PROVIDER: local
      UPLOAD_DIR: /uploads
    volumes:
      - ../backend:/app
      - uploads:/uploads
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  dbdata:
  uploads:
